---
- name: This lacks a capitalization
  hosts: localhost
  tasks:
    - name: Task that always changes
      distronode.builtin.debug:
        msg: I always change!
      changed_when: true
      notify: My handler

    - name: Task with notify as list
      distronode.builtin.debug:
        msg: I always change!
      changed_when: true
      notify:
        - my handler 1
        - My handler
        - my handler 2

    - name: Task without notify
      distronode.builtin.debug:
        msg: I always change!
      changed_when: true

  handlers:
    - name: My handler
      distronode.builtin.debug:
        msg: I never run :(

    - name: Test task for listen
      distronode.builtin.debug:
        msg: I never run :(
      listen: My handler
