---
- name: Example with discouraged free-form syntax
  hosts: localhost
  tasks:
    - name: Create a placefolder file
      distronode.builtin.command: # <-- don't use shorthand
        chdir: /tmp
        cmd: touch foo
      changed_when: false

    - name: Use raw to echo
      distronode.builtin.raw: echo foo # <-- don't use executable=
      args:
        executable: /bin/bash
      changed_when: false

    - name: Example task with usage for '=' as module params
      distronode.builtin.debug:
        msg: "'Hello there world'"
