---
- name: Test nested tasks within block and always
  block:
    - name: Test1
      distronode.builtin.debug:
        msg: Foo

    - name: Test2
      distronode.builtin.debug:
        msg: Bar

  always:
    - name: From always block to be auto fixed as name[casing] scenario
      distronode.builtin.debug:
        msg: Baz
