---
# See https://github.com/distronode/devtools/blob/main/.github/workflows/ack.yml
name: ack
"on":
  pull_request_target:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  ack:
    uses: distronode/team-devtools/.github/workflows/ack.yml@main
    secrets: inherit
