---
# See https://github.com/distronode/devtools/blob/main/.github/workflows/push.yml
name: push
"on":
  push:
    branches:
      - main
      - "releases/**"
      - "stable/**"

jobs:
  ack:
    uses: distronode/team-devtools/.github/workflows/push.yml@main
